version: "3"
services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'  # Management UI
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    environment:
      - NODE_ENV=dev
      - MESSAGE_BROKER_URL=amqp://rabbitmq:5672
    volumes:
      - ./products:/app/products
      - /app/products/node_modules
      - ./logs/products:/app/products/logs
    env_file:
      - ./products/.env.dev
    networks:
      - app-network

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - .:/app
      - /app/shopping/node_modules
      - ./logs/shopping:/app/shopping/logs
    env_file:
      - ./shopping/.env.dev
    networks:
      - app-network

  customers:
    build:
      dockerfile: Dockerfile
      context: ./customers
    container_name: customers
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - ./customers:/app/customers
      - /app/customers/node_modules
      - ./logs/customers:/app/customers/logs
    env_file:
      - ./customers/.env.dev
    networks:
      - app-network

  tenants:
    build:
      dockerfile: Dockerfile
      context: ./tenants
    container_name: tenants
    ports:
      - "8004:8004"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - ./tenants:/app/tenants
      - /app/tenants/node_modules
      - ./logs/tenants:/app/tenants/logs
    env_file:
      - ./tenants/.env.dev
    networks:
      - app-network

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customers
      - tenants
    ports:
      - 80:80
    networks:
      - app-network

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - "products"
      - "shopping"
      - "customers"
      - "tenants"
    volumes:
      - .:/app
      - /app/gateway/node_modules
      - ./logs/gateway:/app/gateway/logs
    env_file:
      - ./gateway/.env.dev
    networks:
      - app-network

  admin:
    build:
      dockerfile: Dockerfile
      context: ./admin
    container_name: admin
    ports:
      - "8005:8005"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - .:/app
      - /app/admin/node_modules
      - ./logs/admin:/app/admin/logs
    env_file:
      - ./admin/.env.dev
    networks:
      - app-network

  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    container_name: payment
    ports:
      - "8006:8006"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - ./payment:/app/payment
      - /app/payment/node_modules
      - ./logs/payment:/app/payment/logs
    env_file:
      - ./payment/.env.dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
