version: "3"
services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'  # Management UI
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    environment:
      - NODE_ENV=dev
      - MESSAGE_BROKER_URL=amqp://rabbitmq:5672
    volumes:
      - ./products:/app/products
      - /app/products/node_modules
      - ./logs/products:/app/products/logs
    env_file:
      - ./products/.env.dev
    networks:
      - app-network

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - .:/app
      - /app/shopping/node_modules
      - ./logs/shopping:/app/shopping/logs
    env_file:
      - ./shopping/.env.dev
    networks:
      - app-network

  customers:
    build:
      dockerfile: Dockerfile
      context: ./customers
    container_name: customers
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - ./customers:/app/customers
      - /app/customers/node_modules
      - ./logs/customers:/app/customers/logs
    env_file:
      - ./customers/.env.dev
    networks:
      - app-network

  tenants:
    build:
      dockerfile: Dockerfile
      context: ./tenants
    container_name: tenants
    ports:
      - "8004:8004"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - ./tenants:/app/tenants
      - /app/tenants/node_modules
      - ./logs/tenants:/app/tenants/logs
    env_file:
      - ./tenants/.env.dev
    networks:
      - app-network

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customers
      - tenants
      - notification
      - admin
      - payment
    ports:
      - 80:80
    networks:
      - app-network

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - "products"
      - "shopping"
      - "customers"
      - "tenants"
    volumes:
      - .:/app
      - /app/gateway/node_modules
      - ./logs/gateway:/app/gateway/logs
    env_file:
      - ./gateway/.env.dev
    networks:
      - app-network
    environment:
      - VENDOR_SERVICE_URL=http://vendor-service:8010

  admin:
    build:
      dockerfile: Dockerfile
      context: ./admin
    container_name: admin
    ports:
      - "8005:8005"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - .:/app
      - /app/admin/node_modules
      - ./logs/admin:/app/admin/logs
    env_file:
      - ./admin/.env.dev
    networks:
      - app-network

  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    container_name: payment
    ports:
      - "8006:8006"
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      nosql-db:
        condition: service_started
    volumes:
      - ./payment:/app/payment
      - /app/payment/node_modules
      - ./logs/payment:/app/payment/logs
    env_file:
      - ./payment/.env.dev
    networks:
      - app-network

  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification
    ports:
      - "8007:8007"
      - "8008:8008"  # Socket.IO port
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    environment:
      - NODE_ENV=dev
      - MONGODB_URI=mongodb://nosql-db:27017/notification-service
    volumes:
      - ./notification:/app/notification
      - /app/notification/node_modules
    env_file:
      - ./notification/.env.dev
    networks:
      - app-network

  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    volumes:
      - ./search:/app/search
      - /app/search/node_modules
    depends_on:
      - nosql-db
      - rabbitmq
      - elasticsearch
    environment:
      - NODE_ENV=dev
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network

  vendor-service:
    build:
      context: ./vendor
      dockerfile: Dockerfile
    container_name: vendor-service
    ports:
      - "8010:8010"
    volumes:
      - ./vendor:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - PORT=8010
      - APP_SECRET=${APP_SECRET}
      - MONGODB_URI=mongodb://nosql-db:27017/vendor-service
      - MESSAGE_BROKER_URL=amqp://rabbitmq:5672
      - EXCHANGE_NAME=B2B_EXCHANGE
      - QUEUE_NAME=vendor_queue
      - STORAGE_TYPE=local
      - UPLOAD_DIR=./uploads
      - LOG_LEVEL=debug
    depends_on:
      - nosql-db
      - rabbitmq
    networks:
      - app-network
    restart: always

  rfq-service:
    build:
      context: ./rfq
      dockerfile: Dockerfile
    container_name: rfq-service
    ports:
      - "8011:8011"
    volumes:
      - ./rfq:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - PORT=8011
      - MONGODB_URI=mongodb://nosql-db:27017/rfq-service
      - MESSAGE_BROKER_URL=amqp://rabbitmq:5672
      - APP_SECRET=your_app_secret
    depends_on:
      - nosql-db
      - rabbitmq
    networks:
      - app-network
    restart: unless-stopped

volumes:
  esdata:
    driver: local

networks:
  app-network:
    driver: bridge
